### ISSUE TITLE
uninstall crash fstab external HDD

### ISSUE THREAD

**Issue by noppe91** [morrolinux/mpradio#24]
Hello,

i installed this on my Raspberry Pi 2 raspbian Jessie. And now my external Harddrive cant be mounted via fstab. Do you have any idea how i can solve this?

I already deleted the backup udev files.

thank you very much.

uname -a
Linux raspberrypi 4.9.78-v7+ #1084 SMP Thu Jan 25 18:05:49 GMT 2018 armv7l GNU/Linux

**Comment by morrolinux** [comment]
Hi, could you check the content of /etc/fstab file?

**Comment by noppe91** [comment]
Thank you for your fast reply. And no i mentioned i forgot some details:
fstab is not mount this USB Drive, but wenn i do `sudo mount -a` it is mounted.

/etc/fstab:
```
proc            /proc           proc    defaults          0       0                                                                                                            
/dev/mmcblk0p1  /boot           vfat    defaults          0       2                                                                                                            
/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1                                                                                                            
UUID=d2027501-c0b2-4391-9c97-39b9bee0f941       /media/USB-HDD  ext4    defaults,nofail   0       0                                                                            
# a swapfile is not a swap partition, so no using swapon|off from here on, use  dphys-swapfile swap[on|off]  for that``
```

**Comment by morrolinux** [comment]
fstab should mount your drive automatically if it is connected at boot-time. 
Make sure you are not attaching the drive AFTER the boot, or it will be perfectly normal that you have to mount -a to mount it.

**Comment by noppe91** [comment]
yeah that´s what it should do :) but since the installation it doesnt work anymore. 
dmesg with mount -a in cron works, and disk is found very early (sda): 
[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Linux version 4.9.78-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) #1084 SMP Thu Jan 25 18:05:49 GMT 2018
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt:Machine model: Raspberry Pi 2 Model B Rev 1.1
[    0.000000] cma: Reserved 8 MiB at 0x3ac00000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 242688
[    0.000000] free_area_init_node: node 0, pgdat 80c6f440, node_mem_map ba3a1000
[    0.000000]   Normal zone: 2133 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:31
[    0.000000] percpu: Embedded 14 pages/cpu @ba35c000 s25600 r8192 d23552 u57344
[    0.000000] pcpu-alloc: s25600 r8192 d23552 u57344 alloc=14*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 240555
[    0.000000] Kernel command line: bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=dea
dline rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 940368K/970752K available (7168K kernel code, 486K rwdata, 2012K rodata, 1024K init, 770K bss, 22192K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
    vmalloc : 0xbb800000 - 0xff800000   (1088 MB)
    lowmem  : 0x80000000 - 0xbb400000   ( 948 MB)
    modules : 0x7f000000 - 0x80000000   (  16 MB)
      .text : 0x80008000 - 0x80800000   (8160 kB)
      .init : 0x80b00000 - 0x80c00000   (1024 kB)
      .data : 0x80c00000 - 0x80c798fc   ( 487 kB)
       .bss : 0x80c7b000 - 0x80d3b9a4   ( 771 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000]   Build-time adjustment of leaf fanout to 32.
[    0.000000] NR_IRQS:16 nr_irqs:16 16
[    0.000000] arm_arch_timer: Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000009] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000024] Switching to timer-based delay loop, resolution 52ns
[    0.000339] Console: colour dummy device 80x30
[    0.000361] console [tty1] enabled
[    0.000386] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000408] pid_max: default: 32768 minimum: 301
[    0.000780] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000795] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002084] Disabling memory control group subsystem
[    0.002194] CPU: Testing write buffer coherency: ok
[    0.002246] ftrace: allocating 22402 entries in 66 pages
[    0.053821] CPU0: update cpu_capacity 1024
[    0.053843] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[    0.053889] Setting up static identity map for 0x100000 - 0x100034
[    0.056697] CPU1: update cpu_capacity 1024
[    0.056709] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[    0.057735] CPU2: update cpu_capacity 1024
[    0.057744] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.058739] CPU3: update cpu_capacity 1024
[    0.058749] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[    0.058879] Brought up 4 CPUs
[    0.058894] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.058899] CPU: All CPU(s) started in HYP mode.
[    0.058904] CPU: Virtualization extensions available.
[    0.060011] devtmpfs: initialized
[    0.073647] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.074046] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.074070] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.074849] pinctrl core: initialized pinctrl subsystem
[    0.076128] NET: Registered protocol family 16
[    0.078756] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.089280] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.089291] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.089491] Serial: AMBA PL011 UART driver
[    0.091891] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.175285] bcm2835-dma 3f007000.dma: DMA legacy API manager at bb80d000, dmachans=0x1
[    0.177717] SCSI subsystem initialized
[    0.177925] usbcore: registered new interface driver usbfs
[    0.178026] usbcore: registered new interface driver hub
[    0.178178] usbcore: registered new device driver usb
[    0.183694] raspberrypi-firmware soc:firmware: Attached to firmware from 2018-01-25 18:09
[    0.185464] clocksource: Switched to clocksource arch_sys_counter
[    0.240442] VFS: Disk quotas dquot_6.6.0
[    0.240553] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.240845] FS-Cache: Loaded
[    0.241207] CacheFiles: Loaded
[    0.257722] NET: Registered protocol family 2
[    0.258970] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.259099] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.259287] TCP: Hash tables configured (established 8192 bind 8192)
[    0.259403] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.259460] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.259779] NET: Registered protocol family 1
[    0.260428] RPC: Registered named UNIX socket transport module.
[    0.260438] RPC: Registered udp transport module.
[    0.260444] RPC: Registered tcp transport module.
[    0.260450] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.261579] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[    0.264617] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.283552] FS-Cache: Netfs 'nfs' registered for caching
[    0.284834] NFS: Registering the id_resolver key type
[    0.284875] Key type id_resolver registered
[    0.284882] Key type id_legacy registered
[    0.288245] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    0.288420] io scheduler noop registered
[    0.288428] io scheduler deadline registered (default)
[    0.288796] io scheduler cfq registered
[    0.294485] BCM2708FB: allocated DMA memory fad00000
[    0.294523] BCM2708FB: allocated DMA channel 0 @ bb80d000
[    0.304115] Console: switching to colour frame buffer device 82x26
[    0.311593] bcm2835-rng 3f104000.rng: hwrng registered
[    0.311717] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.312398] vc-sm: Videocore shared memory driver
[    0.332827] brd: module loaded
[    0.344190] loop: module loaded
[    0.344206] Loading iSCSI transport class v2.0-870.
[    0.344961] usbcore: registered new interface driver smsc95xx
[    0.344984] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.573194] Core Release: 2.80a
[    0.573208] Setting default values for core params
[    0.573249] Finished setting default values for core params
[    0.773710] Using Buffer DMA mode
[    0.773718] Periodic Transfer Interrupt Enhancement - disabled
[    0.773724] Multiprocessor Interrupt Enhancement - disabled
[    0.773732] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.773745] Dedicated Tx FIFOs mode
[    0.774235] WARN::dwc_otg_hcd_init:1032: FIQ DMA bounce buffers: virt = 0xbad14000 dma = 0xfad14000 len=9024
[    0.774265] FIQ FSM acceleration enabled for :
Non-periodic Split Transactions                                                                                                                                                                                                                                        
Periodic Split Transactions                                                                                                                                                                                                                                            
High-Speed Isochronous Endpoints                                                                                                                                                                                                                                       
Interrupt/Control Split Transaction hack enabled                                                                                                                                                                                                                       
[    0.774275] dwc_otg: Microframe scheduler enabled
[    0.774334] WARN::hcd_init_fiq:459: FIQ on core 1 at 0x80590b3c
[    0.774346] WARN::hcd_init_fiq:460: FIQ ASM at 0x80590eac length 36
[    0.774360] WARN::hcd_init_fiq:486: MPHI regs_base at 0xbb878000
[    0.774423] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.774471] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.774516] dwc_otg 3f980000.usb: irq 62, io mem 0x00000000
[    0.774567] Init: Port Power? op_state=1
[    0.774572] Init: Power Port (0)
[    0.774878] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    0.774891] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.774901] usb usb1: Product: DWC OTG Controller
[    0.774911] usb usb1: Manufacturer: Linux 4.9.78-v7+ dwc_otg_hcd
[    0.774921] usb usb1: SerialNumber: 3f980000.usb
[    0.776014] hub 1-0:1.0: USB hub found
[    0.776084] hub 1-0:1.0: 1 port detected
[    0.777030] dwc_otg: FIQ enabled
[    0.777037] dwc_otg: NAK holdoff enabled
[    0.777043] dwc_otg: FIQ split-transaction FSM enabled
[    0.777060] Module dwc_common_port init
[    0.777383] usbcore: registered new interface driver usb-storage
[    0.777725] mousedev: PS/2 mouse device common for all mice
[    0.779009] bcm2835-wdt 3f100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.779384] bcm2835-cpufreq: min=600000 max=1000000
[    0.779899] sdhci: Secure Digital Host Controller Interface driver
[    0.779906] sdhci: Copyright(c) Pierre Ossman
[    0.780265] sdhost-bcm2835 3f202000.sdhost: could not get clk, deferring probe
[    0.780509] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.781286] ledtrig-cpu: registered to indicate activity on CPUs
[    0.781473] hidraw: raw HID events driver (C) Jiri Kosina
[    0.781727] usbcore: registered new interface driver usbhid
[    0.781733] usbhid: USB HID core driver
[    0.782725] vchiq: vchiq_init_state: slot_zero = 0xbad80000, is_master = 0
[    0.784339] [vc_sm_connected_init]: start
[    0.793094] [vc_sm_connected_init]: end - returning 0
[    0.793556] Initializing XFRM netlink socket
[    0.793588] NET: Registered protocol family 17
[    0.793743] Key type dns_resolver registered
[    0.794201] Registering SWP/SWPB emulation handler
[    0.795138] registered taskstats version 1
[    0.801938] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.802036] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 87, base_baud = 0) is a PL011 rev2
[    0.802101] console [ttyAMA0] enabled
[    0.804131] sdhost: log_buf @ bad13000 (fad13000)
[    0.875512] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.875689] of_cfs_init
[    0.876100] of_cfs_init: OK
[    0.876866] Waiting for root device /dev/mmcblk0p2...
[    0.942524] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.944422] mmc0: new high speed SDHC card at address 0001
[    0.945383] mmcblk0: mmc0:0001 00000 29.8 GiB
[    0.947352]  mmcblk0: p1 p2
[    0.998597] EXT4-fs (mmcblk0p2): INFO: recovery required on readonly filesystem
[    0.998610] EXT4-fs (mmcblk0p2): write access will be enabled during recovery
[    1.005633] Indeed it is in host mode hprt0 = 00021501
[    1.088562] random: fast init done
[    1.205535] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.205733] Indeed it is in host mode hprt0 = 00001101
[    1.420963] EXT4-fs (mmcblk0p2): orphan cleanup on readonly fs
[    1.435950] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    1.435966] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.437036] hub 1-1:1.0: USB hub found
[    1.437188] hub 1-1:1.0: 5 ports detected
[    1.444678] EXT4-fs (mmcblk0p2): 17 orphan inodes deleted
[    1.444689] EXT4-fs (mmcblk0p2): recovery complete
[    1.492935] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    1.493013] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.494047] devtmpfs: mounted
[    1.495983] Freeing unused kernel memory: 1024K
[    1.755538] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.827430] systemd[1]: systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
[    1.827927] systemd[1]: Detected architecture 'arm'.
[    1.885932] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    1.885950] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.889061] smsc95xx v1.0.5
[    1.947062] NET: Registered protocol family 10
[    1.949021] systemd[1]: Inserted module 'ipv6'
[    1.951336] systemd[1]: Set hostname to <raspberrypi>.
[    1.980989] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:a1:c7:40
[    2.049046] uart-pl011 3f201000.serial: no DMA platform data
[    2.439119] systemd-sysv-generator[95]: Overwriting existing symlink /run/systemd/generator.late/twonkyserver.service with real service
[    2.465553] usb 1-1.5: new high-speed USB device number 4 using dwc_otg
[    2.601262] usb 1-1.5: New USB device found, idVendor=2109, idProduct=0701
[    2.601281] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.601292] usb 1-1.5: Product: External USB 3.0
[    2.601302] usb 1-1.5: Manufacturer: Intenso
[    2.601312] usb 1-1.5: SerialNumber: 20130302005313
[    2.603433] usb-storage 1-1.5:1.0: USB Mass Storage device detected
[    2.604455] scsi host0: usb-storage 1-1.5:1.0
[    2.636821] systemd[1]: [/lib/systemd/system/mpd.service:17] Unknown lvalue 'ControlGroup' in section 'Service'
[    2.636913] systemd[1]: [/lib/systemd/system/mpd.service:20] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
[    2.781939] systemd[1]: Expecting device dev-ttyAMA0.device...
[    2.782456] systemd[1]: Starting Forward Password Requests to Wall Directory Watch.
[    2.782784] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    2.782890] systemd[1]: Starting Remote File Systems (Pre).
[    2.979163] fuse init (API version 7.26)
[    3.361132] systemd-udevd[147]: starting version 215
[    3.683428] scsi 0:0:0:0: Direct-Access     Intenso  External USB 3.0 0006 PQ: 0 ANSI: 6
[    3.688752] sd 0:0:0:0: [sda] 732566646 4096-byte logical blocks: (3.00 TB/2.73 TiB)
[    3.689369] sd 0:0:0:0: [sda] Write Protect is off
[    3.689394] sd 0:0:0:0: [sda] Mode Sense: 03 00 00 00
[    3.689989] sd 0:0:0:0: [sda] No Caching mode page found
[    3.690005] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    3.929203] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    4.086283] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    4.401294] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    4.492803] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[    4.591505] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[    4.591764] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[    4.664787] systemd-journald[141]: Received request to flush runtime journal from PID 1
[    6.107859] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[    6.109389] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[    6.584737] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
[    7.420778] Process accounting resumed
[    9.743557] NFSD: Using /var/lib/nfs/v4recovery as the NFSv4 state recovery directory
[    9.764959] NFSD: starting 90-second grace period (net 80c65380)
[   13.060877]  sda: sda1
[   13.166043] random: crng init done
[   13.168004] sd 0:0:0:0: [sda] Attached SCSI disk
[   15.764655] ip_tables: (C) 2000-2006 Netfilter Core Team
[   16.341666] EXT4-fs (sda1): recovery complete
[   16.342219] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[   22.530944] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   22.648270] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   23.023597] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   23.828799] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   23.829064] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   25.358806] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   25.360482] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1

**Comment by morrolinux** [comment]
Well that's weird: with both mpradio installed or removed, there's really nothing that should interfere with a simple fstab rule/entry. Nothing in the code / nor in the install/removal procedure and so on.. I have to say to me, il really looks like a generic Linux issue, take a look at some guy having the very same issue in similar (random) circumstances : https://superuser.com/questions/439966/why-is-my-usb-drive-not-mounted-during-startup
maybe try adding "auto" to the mount options?

**Comment by morrolinux** [comment]
Seems like there's nothing left to say. Please reopen if needed
