### ISSUE TITLE
Retrieval of song metadata during (bluetooth) playback

### ISSUE THREAD

**Issue by Hurricos** [morrolinux/mpradio#29]
As far as I can tell, in order to seamlessly transmit music metadata from a BT media source, we would need to set up the AVRCP protocol between the device and the Pi. I have not done quite enough research to know whether this is the most platform-agnostic means (bar building companion apps), let alone whether it will work, but I did notice you did some work with file transfers over BT, so you're probably on a similar page as I am.  I was previously under the impression that A2DP was a superset of AVRCP, but I've (thankfully) been corrected -- thankfully, since bluealsa does not appear to support it natively yet.

I may have the time to implement retrieving songnames from music metadata when playing from storage. There may be some trouble if using `mp3tag`, as in my experience it seems to choke on anything but the most standard ID3 tags; even album art can confuse it.

**Comment by morrolinux** [comment]
Alright that's good news you bring be me here, but please do not open issues for it ;-)
it would be great if you want to contribute adding some features, I'll wait for your PR anytime
Closing the issue for the moment..
