### ISSUE TITLE
Why is the install script blacklisting ipv6?

### ISSUE THREAD

**Issue by miegl** [morrolinux/mpradio#40]
I don't quite understand why mpradio needs ipv6 to be blacklisted.

**Comment by morrolinux** [comment]
Oh, right. I must have forgotten to remove that blacklist command. 
mpradio used to relay on pulseaudio for the bluetooth playback feature, but pulseaudio was a total mess, and fore some reason (among all of the other problems it had) IPv6 enabled was a serious problem for pulseaudio 💯 
Thanks for remembering me thought, I'm going to remove it
