### ISSUE TITLE
Issues installing and removing

### ISSUE THREAD

**Issue by whoodini** [morrolinux/mpradio#42]
Hi,
i had a few Bluetooth FM Transmitters with RDS but none of them can supply song info from Bluetooth over FM-RDS, only from microSD card. Im hopping that this software can do that.

Let me explain what I hope/wish/need this software to do:
Stream music (in stereo) from phone via bluetooth to Pi3 and then to car stereo with artist name and song title ( scrolling (preferably) or artist name (3-5 secs) and then song name (3-5 secs) ) via FM-RDS.

I had a rPi3 lying around pointlessly and did a clean install, some update, upgrade and dist-upgrade. Then went directly and installed mpradio but I had some issues.
After that I removed it and installed it again and had the same issues again (as far as I can tell).

Installation:
[installing.txt](https://github.com/morrolinux/mpradio/files/2238772/installing.txt)

Removing:
[removing.txt](https://github.com/morrolinux/mpradio/files/2238773/removing.txt)

I am a beginner with PI's and Linux. No clues on debugging.

PS I've commented the reboot part out of the installer, so that I can have the debug code.

**Comment by morrolinux** [comment]
Well don't count on it... I'm sorry but the feature you ask for is not supported and probably will never be, as it seems the work needed is far more than the benefit gained, and, a part from me, no one else is contributing on the repo towards that direction
