### ISSUE TITLE
Open source the Android app

### ISSUE THREAD

**Issue by tester962** [morrolinux/mpradio#43]
Hi! Can you please upload the source code of the Android app?
It crashes on my J510FN with Android 7.1 .

**Comment by morrolinux** [comment]
Sure man no problem. Actually I'm on a vacation so I'm not really comfortable doing it, but you can search for "telecomando" on gitlab, the repo is already public.
Keep me updated on your progress and good luck with it :)

**Comment by tester962** [comment]
Thanks!

**Comment by morrolinux** [comment]
Hello, I've published the app here on GItHub
