### ISSUE TITLE
not detecting bluetooth devices

### ISSUE THREAD

**Issue by dpavle** [morrolinux/mpradio#48]
pi@raspberrypi:~ $ systemctl status mpradio
● mpradio.service - Morrolinux Pirate Radio
   Loaded: loaded (/etc/systemd/system/mpradio.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-10-17 20:08:43 CEST; 1min 53s ago
 Main PID: 4817 (mpradio)
   CGroup: /system.slice/mpradio.service
           ├─4817 /bin/mpradio
           ├─4835 bash -c dd bs=40k skip=130 if="/pirateradio/migos.mp3" | sox -v 1 -r 44100 -G  -t mp3 - -t wav -  | /usr/local/bin/pi_fm_rds -ctl /home/pi/rds_ctl -ps "Bad and Boujee (feat. Lil Uzi Vert)" -rt "Bad and Boujee (feat. Lil
           ├─4836 dd bs=40k skip=130 if=/pirateradio/migos.mp3
           ├─4837 sox -v 1 -r 44100 -G -t mp3 - -t wav -
           └─4838 /usr/local/bin/pi_fm_rds -ctl /home/pi/rds_ctl -ps Bad and Boujee (feat. Lil Uzi Vert) -rt Bad and Boujee (feat. Lil Uzi Vert) -audio - -freq 87.5

Oct 17 20:08:45 raspberrypi bash[4817]: Treble: 0
Oct 17 20:08:45 raspberrypi bash[4817]: no bluetooth device provided, playing mp3s...
Oct 17 20:08:45 raspberrypi bash[4817]: CONTROL_PIPE_SETUPAdding: /pirateradio/migos.mp3
Oct 17 20:08:45 raspberrypi bash[4817]: PLAY: /pirateradio/migos.mp3
Oct 17 20:08:45 raspberrypi bash[4817]: FORMAT: mp3
Oct 17 20:08:46 raspberrypi bash[4817]: FILE SIZE: 13837107 DURATION: 343.267 BS: 40
Oct 17 20:08:46 raspberrypi bash[4817]: seeking the track...
Oct 17 20:08:46 raspberrypi bash[4817]: setting audio output to fm
Oct 17 20:08:46 raspberrypi bash[4817]: CMDLINE: dd bs=40k skip=130 if="/pirateradio/migos.mp3" | sox -v 1 -r 44100 -G  -t mp3 - -t wav -  | /usr/local/bin/pi_fm_rds -ctl /home/pi/rds_ctl -ps "Bad and Boujee (feat. Lil Uzi Vert)" -rt "Ba
Oct 17 20:08:47 raspberrypi bash[4817]: sox WARN wav: Length in output .wav header will be wrong since can't seek to fix it

*FAT32 USB connected with 1 .mp3 file and the config file, Bluetooth connected to my phone.*

**Comment by morrolinux** [comment]
Please provide more details and context

**Comment by dpavle** [comment]
What else do you need?

нед, 28. окт 2018. у 19:24 morrolinux <notifications@github.com> је
написао/ла:

**Comment by morrolinux** [comment]
Should be fixed with #58
Reopen if needed
