### ISSUE TITLE
Raspberry pi 3 not transmitting audio from iphone

### ISSUE THREAD

**Issue by Blackbeard25** [morrolinux/mpradio#54]
i am trying this on the raspberry pi 3 using its built in bluetooth. My iPhone is paired and connects just fine but when I try to play audio from my phone the mpradio service stops. It does play mp3's from a usb but the bluetooth does not work. Please help
Edit:the 1.0 dd image works just fine on my rpi 3, with the mp3’s not playing but Bluetooth works, and was unable to get it running on my pi 0w, as that is my end goal

**Comment by morrolinux** [comment]
Should be fixed with #58 
Reopen if needed
