### ISSUE TITLE
Turn off read only on 1.1 image?

### ISSUE THREAD

**Issue by Jesse27** [morrolinux/mpradio#57]
Hi, how do I turn off read only on 1.1 image?

I tried the roswitch.sh command in the readme but it says no such file or directory.

**Comment by morrolinux** [comment]
You're probably doing it wrong. Have you moved to utilty/ first?

**Comment by Jesse27** [comment]
yes I did, I found another way of doing it, by using the command:

mount -o remount,rw /

**Comment by morrolinux** [comment]
Yeah that was more or less the content of the script we were talking about :)

**Comment by DavidM42** [comment]
A nice addition for future images/setups would be a simple alias in .bashrc to have shortcuts to do this.

**Comment by morrolinux** [comment]
yeah! How come I haven't thought about it before
